__author__ = 'ollie'
__all__= ['generateRosMessages','ROSNode']




from PyQt4.QtCore import Qt, QObject, pyqtSignal, pyqtSlot

import rospy
import roslib
import rosgraph

from roslib.packages import get_pkg_dir
roslib.load_manifest('crazyflieROS')
from crazyflieROS import msg as msgCF
from crazyflieROS.msg import cmd as cmdMSG

import tf


from math import radians
#import logging

from commonTools import hasAllKeys, isGroup, getGroup, getNames


MIN_THRUST = 10000
MAX_THRUST_CMD = 60000.0 # as command to the flie
MAX_THRUST_FLIE  = 65535.0 # as value from the flie
def thrustToPercentage(thrust,flie=True):
    return (float(thrust-MIN_THRUST)/((MAX_THRUST_FLIE if flie else MAX_THRUST_CMD)-MIN_THRUST))*100.0


class ROSNode(QObject):
    """ Important for two things:
        Spamming ROS with crazyflie logs,
        Receiving joystick data
    """

    sig_joydata = pyqtSignal(float, float, float, float, bool) #RPYThrustHover
    sig_joydataRaw = pyqtSignal(float, float, float, int, bool) #RPYThrustHover

    def __init__(self, options, parent=None):
        super(ROSNode, self).__init__(parent)

        self.compiledMsgs = [m for m in dir(msgCF) if m[0]!="_"] # Mmessages that are previously auto-compiled and we can send
        self.options = options
        # Publishers
        self.publishers   = {} #Generated publishers will go here
        self.pub_tf       = tf.TransformBroadcaster()

        # Subscribers
        self.sub_tf    = tf.TransformListener()
        self.sub_joy   = rospy.Subscriber("/cfjoy", cmdMSG, self.receiveJoystick)

        self.master = rosgraph.Master('/rostopic')



    def getTopics(self):
        """ Return a list of published topics """
        #try:
        state = self.master.getSystemState()
        pubs, subs, _ = state
        topics = [t for t, _ in pubs]
        #except socket.error:
        #    raise ROSTopicIOException("Unable to communicate with master!")
        return topics

    def pub(self, group, msg):
        """ Generates publishers if needed """
        if group in self.compiledMsgs:
            if group in self.publishers:
                self.publishers[group].publish(msg)
            else:
                rospy.loginfo('Generating Publisher for topic </cf%d/%s>',self.options.radio, group)
                self.publishers[group] = rospy.Publisher("/cf%d/%s" % (self.options.radio, group), eval('msgCF.'+group+'CF'))
                self.publishers[group].publish(msg)
        else:
            rospy.logerr("Please generate messages: %s.msg does not exist", group)


    def genMsg(self, data, ts,f=lambda x: x):
        """ generates a message using sexy python magic. Supply an optional function to apply to each member"""
        group = getGroup(data)
        msgt = eval("msgCF."+group+"CF")
        msg = msgt()
        msg.header.stamp = ts
        for name in getNames(data):
            setattr(msg, name, f(data[group+"."+name])) # sexy python magic
        return msg



    @pyqtSlot(object, int, object)
    def receiveCrazyflieLog(self, log, tsCF, tsROS):
        """ Handle sending messages to ROS """

        ## SPECIALLY HANDLED MESSAGES
        if isGroup(log, "gyro"):
            self.pub(getGroup(log), self.genMsg(log, tsROS, f=radians))
        elif isGroup(log, "motor", ):
            self.pub(getGroup(log), self.genMsg(log, tsROS, f=thrustToPercentage))
        ## AUTOMATICALLY GENERATED HERE
        else:
            self.pub(getGroup(log), self.genMsg(log, tsROS))

        ##ADITIONALLY HANDLED ROS STUFF
        # spam TF #TODO test this!!
        if isGroup(log, "stabilizer"):
            if hasAllKeys(log,["roll","pitch","yaw"], "stabilizer"):
                self.pub_tf.sendTransform((0, 0, 0),tf.transformations.quaternion_from_euler(
                    radians(log["stabilizer.roll"]),
                    -radians(log["stabilizer.pitch"]),
                    -radians(log["stabilizer.yaw"]),'sxyz'), tsROS, "/cf%d" % self.options.radio, "/cf_xyz")



    def receiveJoystick(self, cmd):
        """ Incoming Joystick Message """
        # Emits callback; probably connected to flie and GUI
        # TODO: have the joydriver.py class integrated in here
        # TODO: send param set request for hover/on off
        self.sig_joydata.emit(cmd.roll, cmd.pitch, cmd.yaw, thrustToPercentage(cmd.thrust,flie=False), cmd.hover)
        self.sig_joydataRaw.emit(cmd.roll, cmd.pitch, cmd.yaw, cmd.thrust, cmd.hover)








def generateRosMessages(toc):
    """ Generates the *.msg files for ROS from the TOC
    """
    if not toc:
        rospy.logwarn("No TOC available to generate ROS messages from")
        return

    path = get_pkg_dir('crazyflieROS')+"/msg/"
    for g in toc.keys():
        makeMsg(g, path, toc[g] )


def makeMsg(name, path, members):
    file = open(path+name+"CF.msg", 'w')
    file.write("#DO NOT EDIT THIS FILE - IT IS AUTO GENERATED. ALL CONTENTS WILL BE REPLACED\n")
    file.write("Header header\n")
    for m in sorted(members.keys()):
        # type, remove the _t or append 32
        t = members[m].ctype[:-2] if members[m].ctype!="float" else members[m].ctype+"32"
        file.write("%s %s\n" % (t, members[m].name))
    file.close()