# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'driverGUI.ui'
#
# Created: Sat Jun  7 00:22:54 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(530, 546)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.progressBar_pktIn = QtGui.QProgressBar(self.centralwidget)
        self.progressBar_pktIn.setMaximum(3000)
        self.progressBar_pktIn.setProperty("value", 0)
        self.progressBar_pktIn.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_pktIn.setInvertedAppearance(False)
        self.progressBar_pktIn.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.progressBar_pktIn.setObjectName(_fromUtf8("progressBar_pktIn"))
        self.gridLayout_2.addWidget(self.progressBar_pktIn, 3, 0, 1, 1)
        self.progressBar_pktOut = QtGui.QProgressBar(self.centralwidget)
        self.progressBar_pktOut.setMaximum(480)
        self.progressBar_pktOut.setProperty("value", 0)
        self.progressBar_pktOut.setObjectName(_fromUtf8("progressBar_pktOut"))
        self.gridLayout_2.addWidget(self.progressBar_pktOut, 3, 2, 1, 1)
        self.progressbar_bat = QtGui.QProgressBar(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressbar_bat.sizePolicy().hasHeightForWidth())
        self.progressbar_bat.setSizePolicy(sizePolicy)
        self.progressbar_bat.setMinimum(3000)
        self.progressbar_bat.setMaximum(4200)
        self.progressbar_bat.setProperty("value", 3000)
        self.progressbar_bat.setTextVisible(True)
        self.progressbar_bat.setInvertedAppearance(False)
        self.progressbar_bat.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.progressbar_bat.setObjectName(_fromUtf8("progressbar_bat"))
        self.gridLayout_2.addWidget(self.progressbar_bat, 0, 2, 1, 1)
        self.progressbar_link = QtGui.QProgressBar(self.centralwidget)
        self.progressbar_link.setMaximum(100)
        self.progressbar_link.setProperty("value", 0)
        self.progressbar_link.setTextVisible(True)
        self.progressbar_link.setObjectName(_fromUtf8("progressbar_link"))
        self.gridLayout_2.addWidget(self.progressbar_link, 1, 2, 1, 1)
        self.comboBox_connect = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_connect.sizePolicy().hasHeightForWidth())
        self.comboBox_connect.setSizePolicy(sizePolicy)
        self.comboBox_connect.setObjectName(_fromUtf8("comboBox_connect"))
        self.comboBox_connect.addItem(_fromUtf8(""))
        self.comboBox_connect.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBox_connect, 1, 0, 1, 1)
        self.pushButton_connect = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_connect.sizePolicy().hasHeightForWidth())
        self.pushButton_connect.setSizePolicy(sizePolicy)
        self.pushButton_connect.setObjectName(_fromUtf8("pushButton_connect"))
        self.gridLayout_2.addWidget(self.pushButton_connect, 0, 0, 1, 1)
        self.progressbar_cpu = QtGui.QProgressBar(self.centralwidget)
        self.progressbar_cpu.setProperty("value", 0)
        self.progressbar_cpu.setInvertedAppearance(False)
        self.progressbar_cpu.setObjectName(_fromUtf8("progressbar_cpu"))
        self.gridLayout_2.addWidget(self.progressbar_cpu, 4, 0, 1, 3)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_param = QtGui.QWidget()
        self.tab_param.setObjectName(_fromUtf8("tab_param"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_param)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget.addTab(self.tab_param, _fromUtf8(""))
        self.tab_log = QtGui.QWidget()
        self.tab_log.setObjectName(_fromUtf8("tab_log"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_log)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tabWidget.addTab(self.tab_log, _fromUtf8(""))
        self.tab_connection = QtGui.QWidget()
        self.tab_connection.setObjectName(_fromUtf8("tab_connection"))
        self.gridLayout = QtGui.QGridLayout(self.tab_connection)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.console = QtGui.QTextEdit(self.tab_connection)
        self.console.setEnabled(True)
        self.console.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.console.setReadOnly(True)
        self.console.setObjectName(_fromUtf8("console"))
        self.gridLayout.addWidget(self.console, 7, 0, 1, 2)
        self.tabWidget.addTab(self.tab_connection, _fromUtf8(""))
        self.tab_info = QtGui.QWidget()
        self.tab_info.setObjectName(_fromUtf8("tab_info"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_info)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.tab_info)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_fwMod = QtGui.QLabel(self.groupBox)
        self.label_fwMod.setObjectName(_fromUtf8("label_fwMod"))
        self.gridLayout_6.addWidget(self.label_fwMod, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_6.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_6.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_fw = QtGui.QLabel(self.groupBox)
        self.label_fw.setObjectName(_fromUtf8("label_fw"))
        self.gridLayout_6.addWidget(self.label_fw, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_6.addWidget(self.label, 2, 0, 1, 1)
        self.label_crv = QtGui.QLabel(self.groupBox)
        self.label_crv.setObjectName(_fromUtf8("label_crv"))
        self.gridLayout_6.addWidget(self.label_crv, 2, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_info)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_41 = QtGui.QLabel(self.groupBox_3)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_5.addWidget(self.label_41, 0, 0, 1, 1)
        self.label_baroFound = QtGui.QLabel(self.groupBox_3)
        self.label_baroFound.setObjectName(_fromUtf8("label_baroFound"))
        self.gridLayout_5.addWidget(self.label_baroFound, 0, 1, 1, 1)
        self.label_43 = QtGui.QLabel(self.groupBox_3)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_5.addWidget(self.label_43, 1, 0, 1, 1)
        self.label_magFound = QtGui.QLabel(self.groupBox_3)
        self.label_magFound.setObjectName(_fromUtf8("label_magFound"))
        self.gridLayout_5.addWidget(self.label_magFound, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_info)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_27 = QtGui.QLabel(self.groupBox_2)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_4.addWidget(self.label_27, 0, 0, 1, 1)
        self.label_baroTest = QtGui.QLabel(self.groupBox_2)
        self.label_baroTest.setObjectName(_fromUtf8("label_baroTest"))
        self.gridLayout_4.addWidget(self.label_baroTest, 0, 1, 1, 1)
        self.label_29 = QtGui.QLabel(self.groupBox_2)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_4.addWidget(self.label_29, 1, 0, 1, 1)
        self.label_magTest = QtGui.QLabel(self.groupBox_2)
        self.label_magTest.setObjectName(_fromUtf8("label_magTest"))
        self.gridLayout_4.addWidget(self.label_magTest, 1, 1, 1, 1)
        self.label_31 = QtGui.QLabel(self.groupBox_2)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_4.addWidget(self.label_31, 2, 0, 1, 1)
        self.label_MPUTest = QtGui.QLabel(self.groupBox_2)
        self.label_MPUTest.setObjectName(_fromUtf8("label_MPUTest"))
        self.gridLayout_4.addWidget(self.label_MPUTest, 2, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.tabWidget.addTab(self.tab_info, _fromUtf8(""))
        self.tab_hud = QtGui.QWidget()
        self.tab_hud.setObjectName(_fromUtf8("tab_hud"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tab_hud)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.tabWidget.addTab(self.tab_hud, _fromUtf8(""))
        self.tab_input = QtGui.QWidget()
        self.tab_input.setObjectName(_fromUtf8("tab_input"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_input)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.checkBox_kill = QtGui.QCheckBox(self.tab_input)
        self.checkBox_kill.setChecked(True)
        self.checkBox_kill.setObjectName(_fromUtf8("checkBox_kill"))
        self.verticalLayout_4.addWidget(self.checkBox_kill)
        self.checkBox_hover = QtGui.QCheckBox(self.tab_input)
        self.checkBox_hover.setObjectName(_fromUtf8("checkBox_hover"))
        self.verticalLayout_4.addWidget(self.checkBox_hover)
        self.checkBox_xmode = QtGui.QCheckBox(self.tab_input)
        self.checkBox_xmode.setObjectName(_fromUtf8("checkBox_xmode"))
        self.verticalLayout_4.addWidget(self.checkBox_xmode)
        self.groupBox_input = QtGui.QGroupBox(self.tab_input)
        self.groupBox_input.setCheckable(True)
        self.groupBox_input.setObjectName(_fromUtf8("groupBox_input"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_input)
        self.gridLayout_8.setVerticalSpacing(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_11 = QtGui.QLabel(self.groupBox_input)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_8.addWidget(self.label_11, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_input)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_8.addWidget(self.label_9, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_input)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_8.addWidget(self.label_2, 1, 0, 1, 1)
        self.doubleSpinBox_r = QtGui.QDoubleSpinBox(self.groupBox_input)
        self.doubleSpinBox_r.setFrame(True)
        self.doubleSpinBox_r.setReadOnly(True)
        self.doubleSpinBox_r.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_r.setMinimum(-90.0)
        self.doubleSpinBox_r.setMaximum(90.0)
        self.doubleSpinBox_r.setObjectName(_fromUtf8("doubleSpinBox_r"))
        self.gridLayout_8.addWidget(self.doubleSpinBox_r, 1, 1, 1, 1)
        self.doubleSpinBox_r_t = QtGui.QDoubleSpinBox(self.groupBox_input)
        self.doubleSpinBox_r_t.setReadOnly(False)
        self.doubleSpinBox_r_t.setMinimum(-90.0)
        self.doubleSpinBox_r_t.setMaximum(90.0)
        self.doubleSpinBox_r_t.setObjectName(_fromUtf8("doubleSpinBox_r_t"))
        self.gridLayout_8.addWidget(self.doubleSpinBox_r_t, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_input)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_8.addWidget(self.label_3, 2, 0, 1, 1)
        self.doubleSpinBox_p = QtGui.QDoubleSpinBox(self.groupBox_input)
        self.doubleSpinBox_p.setFrame(True)
        self.doubleSpinBox_p.setReadOnly(True)
        self.doubleSpinBox_p.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_p.setMinimum(-90.0)
        self.doubleSpinBox_p.setMaximum(90.0)
        self.doubleSpinBox_p.setObjectName(_fromUtf8("doubleSpinBox_p"))
        self.gridLayout_8.addWidget(self.doubleSpinBox_p, 2, 1, 1, 1)
        self.doubleSpinBox_p_t = QtGui.QDoubleSpinBox(self.groupBox_input)
        self.doubleSpinBox_p_t.setReadOnly(False)
        self.doubleSpinBox_p_t.setMinimum(-90.0)
        self.doubleSpinBox_p_t.setMaximum(90.0)
        self.doubleSpinBox_p_t.setObjectName(_fromUtf8("doubleSpinBox_p_t"))
        self.gridLayout_8.addWidget(self.doubleSpinBox_p_t, 2, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_input)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_8.addWidget(self.label_4, 3, 0, 1, 1)
        self.doubleSpinBox_y = QtGui.QDoubleSpinBox(self.groupBox_input)
        self.doubleSpinBox_y.setFrame(True)
        self.doubleSpinBox_y.setReadOnly(True)
        self.doubleSpinBox_y.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_y.setMinimum(-90.0)
        self.doubleSpinBox_y.setMaximum(90.0)
        self.doubleSpinBox_y.setObjectName(_fromUtf8("doubleSpinBox_y"))
        self.gridLayout_8.addWidget(self.doubleSpinBox_y, 3, 1, 1, 1)
        self.doubleSpinBox_y_t = QtGui.QDoubleSpinBox(self.groupBox_input)
        self.doubleSpinBox_y_t.setReadOnly(False)
        self.doubleSpinBox_y_t.setMinimum(-90.0)
        self.doubleSpinBox_y_t.setMaximum(90.0)
        self.doubleSpinBox_y_t.setObjectName(_fromUtf8("doubleSpinBox_y_t"))
        self.gridLayout_8.addWidget(self.doubleSpinBox_y_t, 3, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_input)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_8.addWidget(self.label_5, 4, 0, 1, 1)
        self.doubleSpinBox_t = QtGui.QDoubleSpinBox(self.groupBox_input)
        self.doubleSpinBox_t.setFrame(True)
        self.doubleSpinBox_t.setReadOnly(True)
        self.doubleSpinBox_t.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_t.setMaximum(100.0)
        self.doubleSpinBox_t.setObjectName(_fromUtf8("doubleSpinBox_t"))
        self.gridLayout_8.addWidget(self.doubleSpinBox_t, 4, 1, 1, 1)
        self.doubleSpinBox_t_t = QtGui.QDoubleSpinBox(self.groupBox_input)
        self.doubleSpinBox_t_t.setReadOnly(False)
        self.doubleSpinBox_t_t.setMinimum(-10.0)
        self.doubleSpinBox_t_t.setMaximum(10.0)
        self.doubleSpinBox_t_t.setObjectName(_fromUtf8("doubleSpinBox_t_t"))
        self.gridLayout_8.addWidget(self.doubleSpinBox_t_t, 4, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_input)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_8.addWidget(self.label_6, 5, 0, 1, 1)
        self.label_hover = QtGui.QLabel(self.groupBox_input)
        self.label_hover.setObjectName(_fromUtf8("label_hover"))
        self.gridLayout_8.addWidget(self.label_hover, 5, 2, 1, 1)
        self.doubleSpinBox_asl = QtGui.QDoubleSpinBox(self.groupBox_input)
        self.doubleSpinBox_asl.setFrame(True)
        self.doubleSpinBox_asl.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_asl.setMinimum(-200.0)
        self.doubleSpinBox_asl.setMaximum(2000.0)
        self.doubleSpinBox_asl.setObjectName(_fromUtf8("doubleSpinBox_asl"))
        self.gridLayout_8.addWidget(self.doubleSpinBox_asl, 5, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_input)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab_input, _fromUtf8(""))
        self.tab_config = QtGui.QWidget()
        self.tab_config.setObjectName(_fromUtf8("tab_config"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_config)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.scrollArea = QtGui.QScrollArea(self.tab_config)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setMidLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 492, 567))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_3 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.checkBox_guiHZ = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_guiHZ.setChecked(True)
        self.checkBox_guiHZ.setObjectName(_fromUtf8("checkBox_guiHZ"))
        self.gridLayout_3.addWidget(self.checkBox_guiHZ, 3, 0, 1, 1)
        self.horizontalSlider_guiHZ = QtGui.QSlider(self.scrollAreaWidgetContents)
        self.horizontalSlider_guiHZ.setMinimum(1)
        self.horizontalSlider_guiHZ.setMaximum(60)
        self.horizontalSlider_guiHZ.setPageStep(5)
        self.horizontalSlider_guiHZ.setProperty("value", 10)
        self.horizontalSlider_guiHZ.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_guiHZ.setTickPosition(QtGui.QSlider.TicksBelow)
        self.horizontalSlider_guiHZ.setObjectName(_fromUtf8("horizontalSlider_guiHZ"))
        self.gridLayout_3.addWidget(self.horizontalSlider_guiHZ, 3, 1, 1, 1)
        self.spinBox_guiHZ = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBox_guiHZ.setMinimum(1)
        self.spinBox_guiHZ.setMaximum(60)
        self.spinBox_guiHZ.setSingleStep(5)
        self.spinBox_guiHZ.setProperty("value", 10)
        self.spinBox_guiHZ.setObjectName(_fromUtf8("spinBox_guiHZ"))
        self.gridLayout_3.addWidget(self.spinBox_guiHZ, 3, 2, 1, 1)
        self.checkBox_pktHZ = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_pktHZ.setChecked(True)
        self.checkBox_pktHZ.setObjectName(_fromUtf8("checkBox_pktHZ"))
        self.gridLayout_3.addWidget(self.checkBox_pktHZ, 4, 0, 1, 1)
        self.horizontalSlider_pktHZ = QtGui.QSlider(self.scrollAreaWidgetContents)
        self.horizontalSlider_pktHZ.setMinimum(0)
        self.horizontalSlider_pktHZ.setMaximum(30)
        self.horizontalSlider_pktHZ.setSingleStep(5)
        self.horizontalSlider_pktHZ.setPageStep(10)
        self.horizontalSlider_pktHZ.setProperty("value", 5)
        self.horizontalSlider_pktHZ.setSliderPosition(5)
        self.horizontalSlider_pktHZ.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_pktHZ.setTickPosition(QtGui.QSlider.TicksBelow)
        self.horizontalSlider_pktHZ.setTickInterval(5)
        self.horizontalSlider_pktHZ.setObjectName(_fromUtf8("horizontalSlider_pktHZ"))
        self.gridLayout_3.addWidget(self.horizontalSlider_pktHZ, 4, 1, 1, 1)
        self.spinBox_pktHZ = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBox_pktHZ.setPrefix(_fromUtf8(""))
        self.spinBox_pktHZ.setMinimum(1)
        self.spinBox_pktHZ.setMaximum(30)
        self.spinBox_pktHZ.setSingleStep(5)
        self.spinBox_pktHZ.setProperty("value", 5)
        self.spinBox_pktHZ.setObjectName(_fromUtf8("spinBox_pktHZ"))
        self.gridLayout_3.addWidget(self.spinBox_pktHZ, 4, 2, 1, 1)
        self.checkBox_logHZ = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_logHZ.setChecked(True)
        self.checkBox_logHZ.setObjectName(_fromUtf8("checkBox_logHZ"))
        self.gridLayout_3.addWidget(self.checkBox_logHZ, 5, 0, 1, 1)
        self.horizontalSlider_logHZ = QtGui.QSlider(self.scrollAreaWidgetContents)
        self.horizontalSlider_logHZ.setMinimum(1)
        self.horizontalSlider_logHZ.setMaximum(5)
        self.horizontalSlider_logHZ.setPageStep(1)
        self.horizontalSlider_logHZ.setProperty("value", 2)
        self.horizontalSlider_logHZ.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_logHZ.setTickPosition(QtGui.QSlider.TicksBelow)
        self.horizontalSlider_logHZ.setObjectName(_fromUtf8("horizontalSlider_logHZ"))
        self.gridLayout_3.addWidget(self.horizontalSlider_logHZ, 5, 1, 1, 1)
        self.spinBox_logHZ = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBox_logHZ.setMinimum(1)
        self.spinBox_logHZ.setMaximum(5)
        self.spinBox_logHZ.setProperty("value", 2)
        self.spinBox_logHZ.setObjectName(_fromUtf8("spinBox_logHZ"))
        self.gridLayout_3.addWidget(self.spinBox_logHZ, 5, 2, 1, 1)
        self.checkBox_AI = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_AI.setChecked(True)
        self.checkBox_AI.setObjectName(_fromUtf8("checkBox_AI"))
        self.gridLayout_3.addWidget(self.checkBox_AI, 6, 0, 1, 1)
        self.horizontalSlider_AI = QtGui.QSlider(self.scrollAreaWidgetContents)
        self.horizontalSlider_AI.setMinimum(0)
        self.horizontalSlider_AI.setMaximum(60)
        self.horizontalSlider_AI.setSingleStep(5)
        self.horizontalSlider_AI.setPageStep(10)
        self.horizontalSlider_AI.setProperty("value", 30)
        self.horizontalSlider_AI.setSliderPosition(30)
        self.horizontalSlider_AI.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_AI.setTickPosition(QtGui.QSlider.TicksBelow)
        self.horizontalSlider_AI.setTickInterval(5)
        self.horizontalSlider_AI.setObjectName(_fromUtf8("horizontalSlider_AI"))
        self.gridLayout_3.addWidget(self.horizontalSlider_AI, 6, 1, 1, 1)
        self.spinBox_AIHZ = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBox_AIHZ.setPrefix(_fromUtf8(""))
        self.spinBox_AIHZ.setMinimum(1)
        self.spinBox_AIHZ.setMaximum(60)
        self.spinBox_AIHZ.setSingleStep(5)
        self.spinBox_AIHZ.setProperty("value", 30)
        self.spinBox_AIHZ.setObjectName(_fromUtf8("spinBox_AIHZ"))
        self.gridLayout_3.addWidget(self.spinBox_AIHZ, 6, 2, 1, 1)
        self.checkBox_yaw = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_yaw.setObjectName(_fromUtf8("checkBox_yaw"))
        self.gridLayout_3.addWidget(self.checkBox_yaw, 7, 0, 1, 1)
        self.horizontalSlider_yaw = QtGui.QSlider(self.scrollAreaWidgetContents)
        self.horizontalSlider_yaw.setEnabled(False)
        self.horizontalSlider_yaw.setMinimum(-1800)
        self.horizontalSlider_yaw.setMaximum(1800)
        self.horizontalSlider_yaw.setSingleStep(1)
        self.horizontalSlider_yaw.setPageStep(5)
        self.horizontalSlider_yaw.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_yaw.setTickPosition(QtGui.QSlider.TicksBelow)
        self.horizontalSlider_yaw.setTickInterval(450)
        self.horizontalSlider_yaw.setObjectName(_fromUtf8("horizontalSlider_yaw"))
        self.gridLayout_3.addWidget(self.horizontalSlider_yaw, 7, 1, 1, 1)
        self.doubleSpinBox_yaw = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.doubleSpinBox_yaw.setEnabled(False)
        self.doubleSpinBox_yaw.setMinimum(-180.0)
        self.doubleSpinBox_yaw.setMaximum(180.0)
        self.doubleSpinBox_yaw.setSingleStep(0.1)
        self.doubleSpinBox_yaw.setObjectName(_fromUtf8("doubleSpinBox_yaw"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_yaw, 7, 2, 1, 1)
        self.checkBox_ground = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_ground.setObjectName(_fromUtf8("checkBox_ground"))
        self.gridLayout_3.addWidget(self.checkBox_ground, 9, 0, 1, 1)
        self.groupBox_baro = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_baro.setEnabled(True)
        self.groupBox_baro.setCheckable(True)
        self.groupBox_baro.setChecked(False)
        self.groupBox_baro.setObjectName(_fromUtf8("groupBox_baro"))
        self.gridLayout_11 = QtGui.QGridLayout(self.groupBox_baro)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.comboBox_baro = QtGui.QComboBox(self.groupBox_baro)
        self.comboBox_baro.setEnabled(False)
        self.comboBox_baro.setObjectName(_fromUtf8("comboBox_baro"))
        self.comboBox_baro.addItem(_fromUtf8(""))
        self.gridLayout_11.addWidget(self.comboBox_baro, 0, 0, 1, 1)
        self.pushButton_baro = QtGui.QPushButton(self.groupBox_baro)
        self.pushButton_baro.setEnabled(False)
        self.pushButton_baro.setObjectName(_fromUtf8("pushButton_baro"))
        self.gridLayout_11.addWidget(self.pushButton_baro, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_baro, 11, 0, 1, 3)
        self.groupBox_ros = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_ros.setCheckable(True)
        self.groupBox_ros.setObjectName(_fromUtf8("groupBox_ros"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_ros)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.checkBox_rosPID = QtGui.QCheckBox(self.groupBox_ros)
        self.checkBox_rosPID.setChecked(True)
        self.checkBox_rosPID.setObjectName(_fromUtf8("checkBox_rosPID"))
        self.gridLayout_10.addWidget(self.checkBox_rosPID, 0, 2, 1, 1)
        self.checkBox_rosLog = QtGui.QCheckBox(self.groupBox_ros)
        self.checkBox_rosLog.setChecked(True)
        self.checkBox_rosLog.setObjectName(_fromUtf8("checkBox_rosLog"))
        self.gridLayout_10.addWidget(self.checkBox_rosLog, 0, 0, 1, 1)
        self.checkBox_rosCmd = QtGui.QCheckBox(self.groupBox_ros)
        self.checkBox_rosCmd.setChecked(True)
        self.checkBox_rosCmd.setObjectName(_fromUtf8("checkBox_rosCmd"))
        self.gridLayout_10.addWidget(self.checkBox_rosCmd, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_ros, 12, 0, 1, 3)
        spacerItem2 = QtGui.QSpacerItem(20, 38, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 13, 0, 1, 1)
        self.pushButton_ground = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_ground.setEnabled(False)
        self.pushButton_ground.setObjectName(_fromUtf8("pushButton_ground"))
        self.gridLayout_3.addWidget(self.pushButton_ground, 10, 1, 1, 2)
        self.doubleSpinBox_ground = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.doubleSpinBox_ground.setEnabled(False)
        self.doubleSpinBox_ground.setMinimum(-200.0)
        self.doubleSpinBox_ground.setMaximum(1200.0)
        self.doubleSpinBox_ground.setSingleStep(0.1)
        self.doubleSpinBox_ground.setObjectName(_fromUtf8("doubleSpinBox_ground"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_ground, 9, 1, 1, 2)
        self.pushButton_north = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_north.setEnabled(False)
        self.pushButton_north.setObjectName(_fromUtf8("pushButton_north"))
        self.gridLayout_3.addWidget(self.pushButton_north, 8, 1, 1, 2)
        self.checkBox_startupConnect = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_startupConnect.setToolTip(_fromUtf8(""))
        self.checkBox_startupConnect.setChecked(True)
        self.checkBox_startupConnect.setObjectName(_fromUtf8("checkBox_startupConnect"))
        self.gridLayout_3.addWidget(self.checkBox_startupConnect, 2, 0, 1, 3)
        self.checkBox_reconnect = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_reconnect.setToolTip(_fromUtf8(""))
        self.checkBox_reconnect.setObjectName(_fromUtf8("checkBox_reconnect"))
        self.gridLayout_3.addWidget(self.checkBox_reconnect, 1, 0, 1, 2)
        self.checkBox_beep = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_beep.setToolTip(_fromUtf8(""))
        self.checkBox_beep.setObjectName(_fromUtf8("checkBox_beep"))
        self.gridLayout_3.addWidget(self.checkBox_beep, 0, 0, 1, 3)
        self.pushButton_genRosMsg = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_genRosMsg.setEnabled(False)
        self.pushButton_genRosMsg.setObjectName(_fromUtf8("pushButton_genRosMsg"))
        self.gridLayout_3.addWidget(self.pushButton_genRosMsg, 14, 0, 1, 3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab_config, _fromUtf8(""))
        self.tab_joystick = QtGui.QWidget()
        self.tab_joystick.setObjectName(_fromUtf8("tab_joystick"))
        self.label_20 = QtGui.QLabel(self.tab_joystick)
        self.label_20.setGeometry(QtCore.QRect(20, 10, 505, 17))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.tabWidget.addTab(self.tab_joystick, _fromUtf8(""))
        self.tab_tracking = QtGui.QWidget()
        self.tab_tracking.setObjectName(_fromUtf8("tab_tracking"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_tracking)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.tabWidget.addTab(self.tab_tracking, _fromUtf8(""))
        self.tabSync = QtGui.QWidget()
        self.tabSync.setObjectName(_fromUtf8("tabSync"))
        self.gridLayout_12 = QtGui.QGridLayout(self.tabSync)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.groupBox_sync = QtGui.QGroupBox(self.tabSync)
        self.groupBox_sync.setCheckable(True)
        self.groupBox_sync.setObjectName(_fromUtf8("groupBox_sync"))
        self.gridLayout_13 = QtGui.QGridLayout(self.groupBox_sync)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.label_18 = QtGui.QLabel(self.groupBox_sync)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_13.addWidget(self.label_18, 4, 0, 1, 1)
        self.label_flietime = QtGui.QLabel(self.groupBox_sync)
        self.label_flietime.setText(_fromUtf8(""))
        self.label_flietime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_flietime.setObjectName(_fromUtf8("label_flietime"))
        self.gridLayout_13.addWidget(self.label_flietime, 4, 1, 1, 2)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem3, 6, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_sync)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_13.addWidget(self.label_7, 0, 0, 1, 1)
        self.horizontalSlider_syncHz = QtGui.QSlider(self.groupBox_sync)
        self.horizontalSlider_syncHz.setMinimum(1)
        self.horizontalSlider_syncHz.setMaximum(100)
        self.horizontalSlider_syncHz.setSingleStep(5)
        self.horizontalSlider_syncHz.setProperty("value", 5)
        self.horizontalSlider_syncHz.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_syncHz.setTickPosition(QtGui.QSlider.TicksBelow)
        self.horizontalSlider_syncHz.setTickInterval(10)
        self.horizontalSlider_syncHz.setObjectName(_fromUtf8("horizontalSlider_syncHz"))
        self.gridLayout_13.addWidget(self.horizontalSlider_syncHz, 0, 1, 1, 1)
        self.spinBox_syncHz = QtGui.QSpinBox(self.groupBox_sync)
        self.spinBox_syncHz.setMinimum(1)
        self.spinBox_syncHz.setMaximum(100)
        self.spinBox_syncHz.setProperty("value", 5)
        self.spinBox_syncHz.setObjectName(_fromUtf8("spinBox_syncHz"))
        self.gridLayout_13.addWidget(self.spinBox_syncHz, 0, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_sync)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_13.addWidget(self.label_14, 2, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_sync)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_13.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_cputime = QtGui.QLabel(self.groupBox_sync)
        self.label_cputime.setText(_fromUtf8(""))
        self.label_cputime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_cputime.setObjectName(_fromUtf8("label_cputime"))
        self.gridLayout_13.addWidget(self.label_cputime, 3, 1, 1, 2)
        self.label_down = QtGui.QLabel(self.groupBox_sync)
        self.label_down.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_down.setText(_fromUtf8(""))
        self.label_down.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_down.setObjectName(_fromUtf8("label_down"))
        self.gridLayout_13.addWidget(self.label_down, 2, 1, 1, 2)
        self.label_15 = QtGui.QLabel(self.groupBox_sync)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_13.addWidget(self.label_15, 3, 0, 1, 1)
        self.label_up = QtGui.QLabel(self.groupBox_sync)
        self.label_up.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_up.setText(_fromUtf8(""))
        self.label_up.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_up.setObjectName(_fromUtf8("label_up"))
        self.gridLayout_13.addWidget(self.label_up, 1, 1, 1, 2)
        self.label_19 = QtGui.QLabel(self.groupBox_sync)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_13.addWidget(self.label_19, 5, 0, 1, 1)
        self.label_difftime = QtGui.QLabel(self.groupBox_sync)
        self.label_difftime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_difftime.setObjectName(_fromUtf8("label_difftime"))
        self.gridLayout_13.addWidget(self.label_difftime, 5, 1, 1, 2)
        self.gridLayout_12.addWidget(self.groupBox_sync, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabSync, _fromUtf8(""))
        self.tab_PID = QtGui.QWidget()
        self.tab_PID.setObjectName(_fromUtf8("tab_PID"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_PID)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.pushButton_2 = QtGui.QPushButton(self.tab_PID)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_7.addWidget(self.pushButton_2, 1, 0, 1, 2)
        self.label_17 = QtGui.QLabel(self.tab_PID)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_7.addWidget(self.label_17, 2, 0, 1, 1)
        self.horizontalSlider_7 = QtGui.QSlider(self.tab_PID)
        self.horizontalSlider_7.setMinimum(0)
        self.horizontalSlider_7.setMaximum(300)
        self.horizontalSlider_7.setSingleStep(1)
        self.horizontalSlider_7.setPageStep(5)
        self.horizontalSlider_7.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_7.setTickPosition(QtGui.QSlider.TicksBelow)
        self.horizontalSlider_7.setTickInterval(50)
        self.horizontalSlider_7.setObjectName(_fromUtf8("horizontalSlider_7"))
        self.gridLayout_7.addWidget(self.horizontalSlider_7, 2, 2, 1, 2)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem4, 5, 0, 1, 4)
        self.comboBox_2 = QtGui.QComboBox(self.tab_PID)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.comboBox_2, 6, 0, 1, 2)
        self.pushButton_4 = QtGui.QPushButton(self.tab_PID)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_7.addWidget(self.pushButton_4, 6, 2, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.tab_PID)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_7.addWidget(self.pushButton_3, 6, 3, 1, 1)
        self.tableWidget = QtGui.QTableWidget(self.tab_PID)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMinimumSize(QtCore.QSize(270, 116))
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 116))
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setAlternatingRowColors(False)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(60)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(60)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.gridLayout_7.addWidget(self.tableWidget, 0, 0, 1, 4)
        self.pushButton = QtGui.QPushButton(self.tab_PID)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_7.addWidget(self.pushButton, 1, 2, 1, 2)
        self.doubleSpinBox_7 = QtGui.QDoubleSpinBox(self.tab_PID)
        self.doubleSpinBox_7.setSuffix(_fromUtf8(""))
        self.doubleSpinBox_7.setMinimum(0.0)
        self.doubleSpinBox_7.setMaximum(3.0)
        self.doubleSpinBox_7.setSingleStep(0.01)
        self.doubleSpinBox_7.setProperty("value", 1.0)
        self.doubleSpinBox_7.setObjectName(_fromUtf8("doubleSpinBox_7"))
        self.gridLayout_7.addWidget(self.doubleSpinBox_7, 2, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.tab_PID)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_7.addWidget(self.label_16, 3, 0, 1, 1)
        self.comboBox = QtGui.QComboBox(self.tab_PID)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.comboBox, 3, 2, 1, 2)
        self.label_13 = QtGui.QLabel(self.tab_PID)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_7.addWidget(self.label_13, 4, 0, 1, 1)
        self.doubleSpinBox_4 = QtGui.QDoubleSpinBox(self.tab_PID)
        self.doubleSpinBox_4.setDecimals(1)
        self.doubleSpinBox_4.setMinimum(0.0)
        self.doubleSpinBox_4.setMaximum(100.0)
        self.doubleSpinBox_4.setObjectName(_fromUtf8("doubleSpinBox_4"))
        self.gridLayout_7.addWidget(self.doubleSpinBox_4, 4, 1, 1, 1)
        self.horizontalSlider_4 = QtGui.QSlider(self.tab_PID)
        self.horizontalSlider_4.setMinimum(0)
        self.horizontalSlider_4.setMaximum(1000)
        self.horizontalSlider_4.setSingleStep(10)
        self.horizontalSlider_4.setPageStep(100)
        self.horizontalSlider_4.setProperty("value", 500)
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setTickPosition(QtGui.QSlider.TicksBelow)
        self.horizontalSlider_4.setTickInterval(250)
        self.horizontalSlider_4.setObjectName(_fromUtf8("horizontalSlider_4"))
        self.gridLayout_7.addWidget(self.horizontalSlider_4, 4, 2, 1, 2)
        self.tabWidget.addTab(self.tab_PID, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 2, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 530, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(9)
        QtCore.QObject.connect(self.groupBox_input, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.doubleSpinBox_r.setVisible)
        QtCore.QObject.connect(self.groupBox_input, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label_2.setVisible)
        QtCore.QObject.connect(self.groupBox_input, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.doubleSpinBox_p.setVisible)
        QtCore.QObject.connect(self.groupBox_input, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.doubleSpinBox_y.setVisible)
        QtCore.QObject.connect(self.groupBox_input, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.doubleSpinBox_t.setVisible)
        QtCore.QObject.connect(self.groupBox_input, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label_6.setVisible)
        QtCore.QObject.connect(self.groupBox_input, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label_5.setVisible)
        QtCore.QObject.connect(self.groupBox_input, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label_4.setVisible)
        QtCore.QObject.connect(self.groupBox_input, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label_3.setVisible)
        QtCore.QObject.connect(self.groupBox_input, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label_hover.setVisible)
        QtCore.QObject.connect(self.groupBox_input, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.doubleSpinBox_r_t.setVisible)
        QtCore.QObject.connect(self.groupBox_input, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.doubleSpinBox_asl.setVisible)
        QtCore.QObject.connect(self.groupBox_input, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.doubleSpinBox_p_t.setVisible)
        QtCore.QObject.connect(self.groupBox_input, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.doubleSpinBox_y_t.setVisible)
        QtCore.QObject.connect(self.groupBox_input, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.doubleSpinBox_t_t.setVisible)
        QtCore.QObject.connect(self.groupBox_input, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label_11.setVisible)
        QtCore.QObject.connect(self.groupBox_input, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label_9.setVisible)
        QtCore.QObject.connect(self.horizontalSlider_guiHZ, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_guiHZ.setValue)
        QtCore.QObject.connect(self.horizontalSlider_pktHZ, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_pktHZ.setValue)
        QtCore.QObject.connect(self.horizontalSlider_logHZ, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_logHZ.setValue)
        QtCore.QObject.connect(self.horizontalSlider_AI, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_AIHZ.setValue)
        QtCore.QObject.connect(self.spinBox_guiHZ, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.horizontalSlider_guiHZ.setValue)
        QtCore.QObject.connect(self.spinBox_pktHZ, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.horizontalSlider_pktHZ.setValue)
        QtCore.QObject.connect(self.spinBox_logHZ, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.horizontalSlider_logHZ.setValue)
        QtCore.QObject.connect(self.spinBox_AIHZ, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.horizontalSlider_AI.setValue)
        QtCore.QObject.connect(self.checkBox_guiHZ, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.horizontalSlider_guiHZ.setEnabled)
        QtCore.QObject.connect(self.checkBox_guiHZ, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.spinBox_guiHZ.setEnabled)
        QtCore.QObject.connect(self.checkBox_pktHZ, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.horizontalSlider_pktHZ.setEnabled)
        QtCore.QObject.connect(self.checkBox_pktHZ, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.spinBox_pktHZ.setEnabled)
        QtCore.QObject.connect(self.checkBox_logHZ, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.horizontalSlider_logHZ.setEnabled)
        QtCore.QObject.connect(self.checkBox_logHZ, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.spinBox_logHZ.setEnabled)
        QtCore.QObject.connect(self.checkBox_AI, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.horizontalSlider_AI.setEnabled)
        QtCore.QObject.connect(self.checkBox_AI, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.spinBox_AIHZ.setEnabled)
        QtCore.QObject.connect(self.checkBox_yaw, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.horizontalSlider_yaw.setEnabled)
        QtCore.QObject.connect(self.checkBox_yaw, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.doubleSpinBox_yaw.setEnabled)
        QtCore.QObject.connect(self.checkBox_yaw, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pushButton_north.setEnabled)
        QtCore.QObject.connect(self.checkBox_ground, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.doubleSpinBox_ground.setEnabled)
        QtCore.QObject.connect(self.checkBox_ground, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.pushButton_ground.setEnabled)
        QtCore.QObject.connect(self.checkBox_pktHZ, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.progressBar_pktIn.setVisible)
        QtCore.QObject.connect(self.checkBox_pktHZ, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.progressBar_pktOut.setVisible)
        QtCore.QObject.connect(self.horizontalSlider_syncHz, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_syncHz.setValue)
        QtCore.QObject.connect(self.spinBox_syncHz, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.horizontalSlider_syncHz.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.progressBar_pktIn.setFormat(_translate("MainWindow", "In Byte/s: %v/%m", None))
        self.progressBar_pktOut.setFormat(_translate("MainWindow", "Out Byte/s: %v/%m", None))
        self.progressbar_bat.setFormat(_translate("MainWindow", "Battery: %v mV", None))
        self.progressbar_link.setFormat(_translate("MainWindow", "Link quality: %p%", None))
        self.comboBox_connect.setItemText(0, _translate("MainWindow", "Test1", None))
        self.comboBox_connect.setItemText(1, _translate("MainWindow", "Test2", None))
        self.pushButton_connect.setText(_translate("MainWindow", "Scan", None))
        self.progressbar_cpu.setFormat(_translate("MainWindow", "CPU Usage %p%", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_param), _translate("MainWindow", "Param", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_log), _translate("MainWindow", "Log", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_connection), _translate("MainWindow", "Console", None))
        self.groupBox.setTitle(_translate("MainWindow", "Version Info", None))
        self.label_fwMod.setText(_translate("MainWindow", "TextLabel", None))
        self.label_8.setText(_translate("MainWindow", "Firmware Modified:", None))
        self.label_10.setText(_translate("MainWindow", "Firmware:", None))
        self.label_fw.setText(_translate("MainWindow", "TextLabel", None))
        self.label.setText(_translate("MainWindow", "Crazyradio Version:", None))
        self.label_crv.setText(_translate("MainWindow", "TextLabel", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Detected Sensors", None))
        self.label_41.setText(_translate("MainWindow", "Barometer:", None))
        self.label_baroFound.setText(_translate("MainWindow", "TextLabel", None))
        self.label_43.setText(_translate("MainWindow", "Magnetometer:", None))
        self.label_magFound.setText(_translate("MainWindow", "TextLabel", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Self Test", None))
        self.label_27.setText(_translate("MainWindow", "Barometer", None))
        self.label_baroTest.setText(_translate("MainWindow", "TextLabel", None))
        self.label_29.setText(_translate("MainWindow", "Magnetometer :", None))
        self.label_magTest.setText(_translate("MainWindow", "TextLabel", None))
        self.label_31.setText(_translate("MainWindow", "MPU Test:", None))
        self.label_MPUTest.setText(_translate("MainWindow", "TextLabel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_info), _translate("MainWindow", "Info", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_hud), _translate("MainWindow", "HUD", None))
        self.checkBox_kill.setText(_translate("MainWindow", "Disable Thrust", None))
        self.checkBox_hover.setText(_translate("MainWindow", "Disable Hover Mode", None))
        self.checkBox_xmode.setText(_translate("MainWindow", "X-Mode", None))
        self.groupBox_input.setTitle(_translate("MainWindow", "Monitor Outputs", None))
        self.label_11.setText(_translate("MainWindow", "Target", None))
        self.label_9.setText(_translate("MainWindow", "Trim", None))
        self.label_2.setText(_translate("MainWindow", "Roll", None))
        self.doubleSpinBox_r.setSuffix(_translate("MainWindow", "°", None))
        self.doubleSpinBox_r_t.setSuffix(_translate("MainWindow", "°", None))
        self.label_3.setText(_translate("MainWindow", "Pitch", None))
        self.doubleSpinBox_p.setSuffix(_translate("MainWindow", "°", None))
        self.doubleSpinBox_p_t.setSuffix(_translate("MainWindow", "°", None))
        self.label_4.setText(_translate("MainWindow", "Yaw", None))
        self.doubleSpinBox_y.setSuffix(_translate("MainWindow", "°/s", None))
        self.doubleSpinBox_y_t.setSuffix(_translate("MainWindow", "°/s", None))
        self.label_5.setText(_translate("MainWindow", "Thrust", None))
        self.doubleSpinBox_t.setSuffix(_translate("MainWindow", "%", None))
        self.doubleSpinBox_t_t.setSuffix(_translate("MainWindow", "%", None))
        self.label_6.setText(_translate("MainWindow", "Hover", None))
        self.label_hover.setText(_translate("MainWindow", "Off", None))
        self.doubleSpinBox_asl.setSuffix(_translate("MainWindow", " m", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_input), _translate("MainWindow", "Input", None))
        self.checkBox_guiHZ.setToolTip(_translate("MainWindow", "Limit the GUI update rate", None))
        self.checkBox_guiHZ.setText(_translate("MainWindow", "Gui HZ", None))
        self.spinBox_guiHZ.setSuffix(_translate("MainWindow", " HZ", None))
        self.checkBox_pktHZ.setToolTip(_translate("MainWindow", "the rate at which the packet in/out throughput is estimated", None))
        self.checkBox_pktHZ.setText(_translate("MainWindow", "Packet HZ", None))
        self.spinBox_pktHZ.setSuffix(_translate("MainWindow", " HZ", None))
        self.checkBox_logHZ.setToolTip(_translate("MainWindow", "The rate at which the log rate estimation is updated", None))
        self.checkBox_logHZ.setText(_translate("MainWindow", "Log HZ", None))
        self.spinBox_logHZ.setSuffix(_translate("MainWindow", " HZ", None))
        self.checkBox_AI.setToolTip(_translate("MainWindow", "AI update rate", None))
        self.checkBox_AI.setText(_translate("MainWindow", "Attitude Indicator", None))
        self.spinBox_AIHZ.setSuffix(_translate("MainWindow", " HZ", None))
        self.checkBox_yaw.setToolTip(_translate("MainWindow", "Add yaw offset", None))
        self.checkBox_yaw.setText(_translate("MainWindow", "Yaw Offset", None))
        self.doubleSpinBox_yaw.setSuffix(_translate("MainWindow", "°", None))
        self.checkBox_ground.setToolTip(_translate("MainWindow", "Use adjusted ground level for barometer", None))
        self.checkBox_ground.setText(_translate("MainWindow", "Ground Sea Level", None))
        self.groupBox_baro.setTitle(_translate("MainWindow", "Advanced Barometer", None))
        self.comboBox_baro.setItemText(0, _translate("MainWindow", "None Detected", None))
        self.pushButton_baro.setText(_translate("MainWindow", "Refresh", None))
        self.groupBox_ros.setTitle(_translate("MainWindow", "Publish To ROS", None))
        self.checkBox_rosPID.setText(_translate("MainWindow", "PID Data", None))
        self.checkBox_rosLog.setText(_translate("MainWindow", "Log Data", None))
        self.checkBox_rosCmd.setText(_translate("MainWindow", "Raw Commands", None))
        self.pushButton_ground.setText(_translate("MainWindow", "Set Ground Level", None))
        self.doubleSpinBox_ground.setSuffix(_translate("MainWindow", "m", None))
        self.pushButton_north.setText(_translate("MainWindow", "Set North", None))
        self.checkBox_startupConnect.setText(_translate("MainWindow", "Connect on startup", None))
        self.checkBox_reconnect.setText(_translate("MainWindow", "Auto Reconnect", None))
        self.checkBox_beep.setText(_translate("MainWindow", "Enable Sounds", None))
        self.pushButton_genRosMsg.setText(_translate("MainWindow", "Generate ROS msgs from ToC", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_config), _translate("MainWindow", "Settings", None))
        self.label_20.setText(_translate("MainWindow", "No joystick data received. Make sure you are publishing on /joy", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_joystick), _translate("MainWindow", "Joystick", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_tracking), _translate("MainWindow", "Tracking", None))
        self.groupBox_sync.setTitle(_translate("MainWindow", "Time Sync", None))
        self.label_18.setText(_translate("MainWindow", "Flie Time", None))
        self.label_7.setText(_translate("MainWindow", "Update Freq", None))
        self.label_14.setText(_translate("MainWindow", "Receive Time", None))
        self.label_12.setText(_translate("MainWindow", "Send Time", None))
        self.label_15.setText(_translate("MainWindow", "CPU Time", None))
        self.label_19.setText(_translate("MainWindow", "Difference", None))
        self.label_difftime.setText(_translate("MainWindow", "TextLabel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSync), _translate("MainWindow", "Sync", None))
        self.pushButton_2.setText(_translate("MainWindow", "Realtime Graph", None))
        self.label_17.setToolTip(_translate("MainWindow", "Rotation added to crazyflie yaw estimation so 0 degrees on the crazyflie is 0 degrees (ie north) in reality", None))
        self.label_17.setText(_translate("MainWindow", "Response", None))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Current", None))
        self.pushButton_4.setText(_translate("MainWindow", "Save Preset", None))
        self.pushButton_3.setText(_translate("MainWindow", "Remove Preset", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Roll & Pitch", None))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Yaw", None))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Thrust", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "P", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "I", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "D", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Min", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Max", None))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Response", None))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("MainWindow", "Graph Response Curves", None))
        self.label_16.setToolTip(_translate("MainWindow", "Rotation added to crazyflie yaw estimation so 0 degrees on the crazyflie is 0 degrees (ie north) in reality", None))
        self.label_16.setText(_translate("MainWindow", "Roll & Pitch Func", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "LINEAR", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "ASIN", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "ATAN", None))
        self.label_13.setToolTip(_translate("MainWindow", "Rotation added to crazyflie yaw estimation so 0 degrees on the crazyflie is 0 degrees (ie north) in reality", None))
        self.label_13.setText(_translate("MainWindow", "Base Thrust", None))
        self.doubleSpinBox_4.setSuffix(_translate("MainWindow", "%", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_PID), _translate("MainWindow", "PID", None))

