# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'driverGUI.ui'
#
# Created: Mon Feb 17 21:17:00 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(416, 527)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_connection = QtGui.QWidget()
        self.tab_connection.setObjectName(_fromUtf8("tab_connection"))
        self.gridLayout = QtGui.QGridLayout(self.tab_connection)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton_connect = QtGui.QPushButton(self.tab_connection)
        self.pushButton_connect.setObjectName(_fromUtf8("pushButton_connect"))
        self.gridLayout.addWidget(self.pushButton_connect, 0, 0, 1, 1)
        self.comboBox_connect = QtGui.QComboBox(self.tab_connection)
        self.comboBox_connect.setObjectName(_fromUtf8("comboBox_connect"))
        self.comboBox_connect.addItem(_fromUtf8(""))
        self.comboBox_connect.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_connect, 0, 1, 1, 1)
        self.progressbar_bat = QtGui.QProgressBar(self.tab_connection)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressbar_bat.sizePolicy().hasHeightForWidth())
        self.progressbar_bat.setSizePolicy(sizePolicy)
        self.progressbar_bat.setMinimum(3000)
        self.progressbar_bat.setMaximum(4200)
        self.progressbar_bat.setProperty("value", 3000)
        self.progressbar_bat.setTextVisible(True)
        self.progressbar_bat.setInvertedAppearance(False)
        self.progressbar_bat.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.progressbar_bat.setObjectName(_fromUtf8("progressbar_bat"))
        self.gridLayout.addWidget(self.progressbar_bat, 4, 0, 1, 2)
        self.progressbar_link = QtGui.QProgressBar(self.tab_connection)
        self.progressbar_link.setMaximum(100)
        self.progressbar_link.setProperty("value", 0)
        self.progressbar_link.setTextVisible(True)
        self.progressbar_link.setObjectName(_fromUtf8("progressbar_link"))
        self.gridLayout.addWidget(self.progressbar_link, 5, 0, 1, 2)
        self.console = QtGui.QTextEdit(self.tab_connection)
        self.console.setEnabled(True)
        self.console.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.console.setReadOnly(True)
        self.console.setObjectName(_fromUtf8("console"))
        self.gridLayout.addWidget(self.console, 8, 0, 1, 2)
        self.progressBar_pktOut = QtGui.QProgressBar(self.tab_connection)
        self.progressBar_pktOut.setMaximum(20)
        self.progressBar_pktOut.setProperty("value", 0)
        self.progressBar_pktOut.setObjectName(_fromUtf8("progressBar_pktOut"))
        self.gridLayout.addWidget(self.progressBar_pktOut, 6, 1, 1, 1)
        self.progressBar_pktIn = QtGui.QProgressBar(self.tab_connection)
        self.progressBar_pktIn.setMaximum(20)
        self.progressBar_pktIn.setProperty("value", 0)
        self.progressBar_pktIn.setObjectName(_fromUtf8("progressBar_pktIn"))
        self.gridLayout.addWidget(self.progressBar_pktIn, 6, 0, 1, 1)
        self.checkBox_kill = QtGui.QCheckBox(self.tab_connection)
        self.checkBox_kill.setObjectName(_fromUtf8("checkBox_kill"))
        self.gridLayout.addWidget(self.checkBox_kill, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_connection, _fromUtf8(""))
        self.tab_config = QtGui.QWidget()
        self.tab_config.setObjectName(_fromUtf8("tab_config"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_config)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.checkBox_beep = QtGui.QCheckBox(self.tab_config)
        self.checkBox_beep.setObjectName(_fromUtf8("checkBox_beep"))
        self.gridLayout_3.addWidget(self.checkBox_beep, 0, 0, 1, 1)
        self.checkBox_reconnect = QtGui.QCheckBox(self.tab_config)
        self.checkBox_reconnect.setObjectName(_fromUtf8("checkBox_reconnect"))
        self.gridLayout_3.addWidget(self.checkBox_reconnect, 1, 0, 1, 3)
        self.checkBox_startupConnect = QtGui.QCheckBox(self.tab_config)
        self.checkBox_startupConnect.setChecked(True)
        self.checkBox_startupConnect.setObjectName(_fromUtf8("checkBox_startupConnect"))
        self.gridLayout_3.addWidget(self.checkBox_startupConnect, 2, 0, 1, 2)
        self.checkBox_pktHZ = QtGui.QCheckBox(self.tab_config)
        self.checkBox_pktHZ.setChecked(True)
        self.checkBox_pktHZ.setObjectName(_fromUtf8("checkBox_pktHZ"))
        self.gridLayout_3.addWidget(self.checkBox_pktHZ, 3, 0, 1, 1)
        self.horizontalSlider_pktHZ = QtGui.QSlider(self.tab_config)
        self.horizontalSlider_pktHZ.setMinimum(0)
        self.horizontalSlider_pktHZ.setMaximum(30)
        self.horizontalSlider_pktHZ.setSingleStep(5)
        self.horizontalSlider_pktHZ.setPageStep(10)
        self.horizontalSlider_pktHZ.setProperty("value", 5)
        self.horizontalSlider_pktHZ.setSliderPosition(5)
        self.horizontalSlider_pktHZ.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_pktHZ.setTickPosition(QtGui.QSlider.TicksBelow)
        self.horizontalSlider_pktHZ.setTickInterval(5)
        self.horizontalSlider_pktHZ.setObjectName(_fromUtf8("horizontalSlider_pktHZ"))
        self.gridLayout_3.addWidget(self.horizontalSlider_pktHZ, 3, 1, 1, 3)
        self.spinBox_pktHZ = QtGui.QSpinBox(self.tab_config)
        self.spinBox_pktHZ.setPrefix(_fromUtf8(""))
        self.spinBox_pktHZ.setMinimum(1)
        self.spinBox_pktHZ.setMaximum(30)
        self.spinBox_pktHZ.setSingleStep(5)
        self.spinBox_pktHZ.setProperty("value", 5)
        self.spinBox_pktHZ.setObjectName(_fromUtf8("spinBox_pktHZ"))
        self.gridLayout_3.addWidget(self.spinBox_pktHZ, 3, 4, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 4, 2, 1, 1)
        self.tabWidget.addTab(self.tab_config, _fromUtf8(""))
        self.tab_param = QtGui.QWidget()
        self.tab_param.setObjectName(_fromUtf8("tab_param"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_param)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget.addTab(self.tab_param, _fromUtf8(""))
        self.tab_log = QtGui.QWidget()
        self.tab_log.setObjectName(_fromUtf8("tab_log"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_log)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tabWidget.addTab(self.tab_log, _fromUtf8(""))
        self.tab_info = QtGui.QWidget()
        self.tab_info.setObjectName(_fromUtf8("tab_info"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_info)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.tab_info)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_fwMod = QtGui.QLabel(self.groupBox)
        self.label_fwMod.setObjectName(_fromUtf8("label_fwMod"))
        self.gridLayout_6.addWidget(self.label_fwMod, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_6.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_6.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_fw = QtGui.QLabel(self.groupBox)
        self.label_fw.setObjectName(_fromUtf8("label_fw"))
        self.gridLayout_6.addWidget(self.label_fw, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_6.addWidget(self.label, 2, 0, 1, 1)
        self.label_crv = QtGui.QLabel(self.groupBox)
        self.label_crv.setObjectName(_fromUtf8("label_crv"))
        self.gridLayout_6.addWidget(self.label_crv, 2, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_info)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_41 = QtGui.QLabel(self.groupBox_3)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_5.addWidget(self.label_41, 0, 0, 1, 1)
        self.label_baroFound = QtGui.QLabel(self.groupBox_3)
        self.label_baroFound.setObjectName(_fromUtf8("label_baroFound"))
        self.gridLayout_5.addWidget(self.label_baroFound, 0, 1, 1, 1)
        self.label_43 = QtGui.QLabel(self.groupBox_3)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_5.addWidget(self.label_43, 1, 0, 1, 1)
        self.label_magFound = QtGui.QLabel(self.groupBox_3)
        self.label_magFound.setObjectName(_fromUtf8("label_magFound"))
        self.gridLayout_5.addWidget(self.label_magFound, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_info)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_27 = QtGui.QLabel(self.groupBox_2)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_4.addWidget(self.label_27, 0, 0, 1, 1)
        self.label_baroTest = QtGui.QLabel(self.groupBox_2)
        self.label_baroTest.setObjectName(_fromUtf8("label_baroTest"))
        self.gridLayout_4.addWidget(self.label_baroTest, 0, 1, 1, 1)
        self.label_29 = QtGui.QLabel(self.groupBox_2)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_4.addWidget(self.label_29, 1, 0, 1, 1)
        self.label_magTest = QtGui.QLabel(self.groupBox_2)
        self.label_magTest.setObjectName(_fromUtf8("label_magTest"))
        self.gridLayout_4.addWidget(self.label_magTest, 1, 1, 1, 1)
        self.label_31 = QtGui.QLabel(self.groupBox_2)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_4.addWidget(self.label_31, 2, 0, 1, 1)
        self.label_MPUTest = QtGui.QLabel(self.groupBox_2)
        self.label_MPUTest.setObjectName(_fromUtf8("label_MPUTest"))
        self.gridLayout_4.addWidget(self.label_MPUTest, 2, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab_info, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 416, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.horizontalSlider_pktHZ, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_pktHZ.setValue)
        QtCore.QObject.connect(self.spinBox_pktHZ, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.horizontalSlider_pktHZ.setValue)
        QtCore.QObject.connect(self.checkBox_pktHZ, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.horizontalSlider_pktHZ.setEnabled)
        QtCore.QObject.connect(self.checkBox_pktHZ, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.spinBox_pktHZ.setEnabled)
        QtCore.QObject.connect(self.checkBox_pktHZ, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.progressBar_pktIn.setVisible)
        QtCore.QObject.connect(self.checkBox_pktHZ, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.progressBar_pktOut.setVisible)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_connect.setText(QtGui.QApplication.translate("MainWindow", "Scan", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_connect.setItemText(0, QtGui.QApplication.translate("MainWindow", "Test1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_connect.setItemText(1, QtGui.QApplication.translate("MainWindow", "Test2", None, QtGui.QApplication.UnicodeUTF8))
        self.progressbar_bat.setFormat(QtGui.QApplication.translate("MainWindow", "Battery: %v mV", None, QtGui.QApplication.UnicodeUTF8))
        self.progressbar_link.setFormat(QtGui.QApplication.translate("MainWindow", "Link quality: %p%", None, QtGui.QApplication.UnicodeUTF8))
        self.progressBar_pktOut.setFormat(QtGui.QApplication.translate("MainWindow", "Packets out/sec: %p", None, QtGui.QApplication.UnicodeUTF8))
        self.progressBar_pktIn.setFormat(QtGui.QApplication.translate("MainWindow", "Packets in/sec: %p", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_kill.setText(QtGui.QApplication.translate("MainWindow", "Kill Switch", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_connection), QtGui.QApplication.translate("MainWindow", "Connection", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_beep.setText(QtGui.QApplication.translate("MainWindow", "Enable Sounds", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_reconnect.setText(QtGui.QApplication.translate("MainWindow", "Auto Reconnect", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_startupConnect.setText(QtGui.QApplication.translate("MainWindow", "Connect on startup", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_pktHZ.setText(QtGui.QApplication.translate("MainWindow", "Packet Rate", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBox_pktHZ.setSuffix(QtGui.QApplication.translate("MainWindow", " HZ", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_config), QtGui.QApplication.translate("MainWindow", "Config", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_param), QtGui.QApplication.translate("MainWindow", "Param", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_log), QtGui.QApplication.translate("MainWindow", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Version Info", None, QtGui.QApplication.UnicodeUTF8))
        self.label_fwMod.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Firmware Modified:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Firmware:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_fw.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Crazyradio Version:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_crv.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Detected Sensors", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("MainWindow", "Barometer:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_baroFound.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("MainWindow", "Magnetometer:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_magFound.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Self Test", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "Barometer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_baroTest.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "Magnetometer :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_magTest.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "MPU Test:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_MPUTest.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_info), QtGui.QApplication.translate("MainWindow", "Info", None, QtGui.QApplication.UnicodeUTF8))

