# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trackerGUI.ui'
#
# Created: Sat Jun  7 00:22:54 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ScrollAreaTracker(object):
    def setupUi(self, ScrollAreaTracker):
        ScrollAreaTracker.setObjectName(_fromUtf8("ScrollAreaTracker"))
        ScrollAreaTracker.resize(585, 763)
        ScrollAreaTracker.setFrameShape(QtGui.QFrame.NoFrame)
        ScrollAreaTracker.setFrameShadow(QtGui.QFrame.Plain)
        ScrollAreaTracker.setLineWidth(0)
        ScrollAreaTracker.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        ScrollAreaTracker.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 585, 763))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox_slam = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_slam.setObjectName(_fromUtf8("groupBox_slam"))
        self.gridLayout.addWidget(self.groupBox_slam, 6, 0, 1, 1)
        self.groupBox_qualisys = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_qualisys.setEnabled(True)
        self.groupBox_qualisys.setObjectName(_fromUtf8("groupBox_qualisys"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_qualisys)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_24 = QtGui.QLabel(self.groupBox_qualisys)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_10.addWidget(self.label_24, 2, 0, 1, 1)
        self.label_23 = QtGui.QLabel(self.groupBox_qualisys)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_10.addWidget(self.label_23, 0, 0, 1, 1)
        self.comboBox_q1 = QtGui.QComboBox(self.groupBox_qualisys)
        self.comboBox_q1.setObjectName(_fromUtf8("comboBox_q1"))
        self.comboBox_q1.addItem(_fromUtf8(""))
        self.comboBox_q1.addItem(_fromUtf8(""))
        self.comboBox_q1.addItem(_fromUtf8(""))
        self.gridLayout_10.addWidget(self.comboBox_q1, 1, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBox_qualisys)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_10.addWidget(self.label_22, 1, 0, 1, 1)
        self.comboBox_q0 = QtGui.QComboBox(self.groupBox_qualisys)
        self.comboBox_q0.setObjectName(_fromUtf8("comboBox_q0"))
        self.comboBox_q0.addItem(_fromUtf8(""))
        self.comboBox_q0.addItem(_fromUtf8(""))
        self.comboBox_q0.addItem(_fromUtf8(""))
        self.gridLayout_10.addWidget(self.comboBox_q0, 0, 1, 1, 1)
        self.doubleSpinBox_6 = QtGui.QDoubleSpinBox(self.groupBox_qualisys)
        self.doubleSpinBox_6.setMaximum(5.0)
        self.doubleSpinBox_6.setSingleStep(0.1)
        self.doubleSpinBox_6.setObjectName(_fromUtf8("doubleSpinBox_6"))
        self.gridLayout_10.addWidget(self.doubleSpinBox_6, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_qualisys, 1, 0, 1, 2)
        self.comboBox_tracker = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox_tracker.setObjectName(_fromUtf8("comboBox_tracker"))
        self.comboBox_tracker.addItem(_fromUtf8(""))
        self.comboBox_tracker.addItem(_fromUtf8(""))
        self.comboBox_tracker.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_tracker, 0, 1, 1, 1)
        self.pushButton_trackStart = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_trackStart.setObjectName(_fromUtf8("pushButton_trackStart"))
        self.gridLayout.addWidget(self.pushButton_trackStart, 0, 0, 1, 1)
        self.groupBox_kinectBG = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_kinectBG.setEnabled(True)
        self.groupBox_kinectBG.setObjectName(_fromUtf8("groupBox_kinectBG"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_kinectBG)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.pushButton_reset = QtGui.QPushButton(self.groupBox_kinectBG)
        self.pushButton_reset.setObjectName(_fromUtf8("pushButton_reset"))
        self.gridLayout_7.addWidget(self.pushButton_reset, 0, 0, 1, 1)
        self.comboBox_kinMethod = QtGui.QComboBox(self.groupBox_kinectBG)
        self.comboBox_kinMethod.setObjectName(_fromUtf8("comboBox_kinMethod"))
        self.comboBox_kinMethod.addItem(_fromUtf8(""))
        self.comboBox_kinMethod.addItem(_fromUtf8(""))
        self.gridLayout_7.addWidget(self.comboBox_kinMethod, 2, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox_kinectBG)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_7.addWidget(self.label_17, 2, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_kinectBG)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_7.addWidget(self.label_11, 4, 0, 1, 1)
        self.doubleSpinBox_kinMaxDepth = QtGui.QDoubleSpinBox(self.groupBox_kinectBG)
        self.doubleSpinBox_kinMaxDepth.setMinimum(2.0)
        self.doubleSpinBox_kinMaxDepth.setMaximum(8.0)
        self.doubleSpinBox_kinMaxDepth.setSingleStep(0.25)
        self.doubleSpinBox_kinMaxDepth.setProperty("value", 4.5)
        self.doubleSpinBox_kinMaxDepth.setObjectName(_fromUtf8("doubleSpinBox_kinMaxDepth"))
        self.gridLayout_7.addWidget(self.doubleSpinBox_kinMaxDepth, 4, 1, 1, 1)
        self.doubleSpinBox_kinObsTime = QtGui.QDoubleSpinBox(self.groupBox_kinectBG)
        self.doubleSpinBox_kinObsTime.setPrefix(_fromUtf8(""))
        self.doubleSpinBox_kinObsTime.setDecimals(1)
        self.doubleSpinBox_kinObsTime.setMinimum(0.5)
        self.doubleSpinBox_kinObsTime.setMaximum(10.0)
        self.doubleSpinBox_kinObsTime.setSingleStep(0.25)
        self.doubleSpinBox_kinObsTime.setProperty("value", 3.5)
        self.doubleSpinBox_kinObsTime.setObjectName(_fromUtf8("doubleSpinBox_kinObsTime"))
        self.gridLayout_7.addWidget(self.doubleSpinBox_kinObsTime, 1, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.groupBox_kinectBG)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_7.addWidget(self.label_18, 1, 0, 1, 1)
        self.progressBar_background = QtGui.QProgressBar(self.groupBox_kinectBG)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar_background.sizePolicy().hasHeightForWidth())
        self.progressBar_background.setSizePolicy(sizePolicy)
        self.progressBar_background.setMaximum(105)
        self.progressBar_background.setProperty("value", -1)
        self.progressBar_background.setObjectName(_fromUtf8("progressBar_background"))
        self.gridLayout_7.addWidget(self.progressBar_background, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_kinectBG)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_7.addWidget(self.label_2, 5, 0, 1, 1)
        self.doubleSpinBox_kinFG = QtGui.QDoubleSpinBox(self.groupBox_kinectBG)
        self.doubleSpinBox_kinFG.setDecimals(1)
        self.doubleSpinBox_kinFG.setMinimum(1.0)
        self.doubleSpinBox_kinFG.setMaximum(100.0)
        self.doubleSpinBox_kinFG.setSingleStep(0.1)
        self.doubleSpinBox_kinFG.setProperty("value", 45.0)
        self.doubleSpinBox_kinFG.setObjectName(_fromUtf8("doubleSpinBox_kinFG"))
        self.gridLayout_7.addWidget(self.doubleSpinBox_kinFG, 5, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_kinectBG, 2, 0, 1, 2)
        self.groupBox_kinectFG = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_kinectFG.setEnabled(True)
        self.groupBox_kinectFG.setObjectName(_fromUtf8("groupBox_kinectFG"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_kinectFG)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.spinBox_kernelSize = QtGui.QSpinBox(self.groupBox_kinectFG)
        self.spinBox_kernelSize.setMaximum(5)
        self.spinBox_kernelSize.setProperty("value", 1)
        self.spinBox_kernelSize.setObjectName(_fromUtf8("spinBox_kernelSize"))
        self.gridLayout_2.addWidget(self.spinBox_kernelSize, 2, 1, 1, 2)
        self.label_21 = QtGui.QLabel(self.groupBox_kinectFG)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_2.addWidget(self.label_21, 5, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_kinectFG)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 1, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBox_kinectFG)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_2.addWidget(self.label_19, 4, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_kinectFG)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 0, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox_kinectFG)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 3, 0, 1, 1)
        self.comboBox_kinDepth = QtGui.QComboBox(self.groupBox_kinectFG)
        self.comboBox_kinDepth.setObjectName(_fromUtf8("comboBox_kinDepth"))
        self.comboBox_kinDepth.addItem(_fromUtf8(""))
        self.comboBox_kinDepth.addItem(_fromUtf8(""))
        self.comboBox_kinDepth.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBox_kinDepth, 5, 1, 2, 2)
        self.doubleSpinBox_tol = QtGui.QDoubleSpinBox(self.groupBox_kinectFG)
        self.doubleSpinBox_tol.setDecimals(1)
        self.doubleSpinBox_tol.setMinimum(2.0)
        self.doubleSpinBox_tol.setMaximum(30.0)
        self.doubleSpinBox_tol.setSingleStep(0.25)
        self.doubleSpinBox_tol.setProperty("value", 4.0)
        self.doubleSpinBox_tol.setObjectName(_fromUtf8("doubleSpinBox_tol"))
        self.gridLayout_2.addWidget(self.doubleSpinBox_tol, 1, 1, 1, 2)
        self.doubleSpinBox_kinDetSize = QtGui.QDoubleSpinBox(self.groupBox_kinectFG)
        self.doubleSpinBox_kinDetSize.setDecimals(1)
        self.doubleSpinBox_kinDetSize.setMinimum(1.0)
        self.doubleSpinBox_kinDetSize.setMaximum(30.0)
        self.doubleSpinBox_kinDetSize.setProperty("value", 6.0)
        self.doubleSpinBox_kinDetSize.setObjectName(_fromUtf8("doubleSpinBox_kinDetSize"))
        self.gridLayout_2.addWidget(self.doubleSpinBox_kinDetSize, 0, 1, 1, 2)
        self.comboBox_prio = QtGui.QComboBox(self.groupBox_kinectFG)
        self.comboBox_prio.setObjectName(_fromUtf8("comboBox_prio"))
        self.comboBox_prio.addItem(_fromUtf8(""))
        self.comboBox_prio.addItem(_fromUtf8(""))
        self.comboBox_prio.addItem(_fromUtf8(""))
        self.comboBox_prio.addItem(_fromUtf8(""))
        self.comboBox_prio.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBox_prio, 4, 1, 1, 2)
        self.spinBox_kernelIter = QtGui.QSpinBox(self.groupBox_kinectFG)
        self.spinBox_kernelIter.setSuffix(_fromUtf8(""))
        self.spinBox_kernelIter.setMaximum(10)
        self.spinBox_kernelIter.setProperty("value", 1)
        self.spinBox_kernelIter.setObjectName(_fromUtf8("spinBox_kernelIter"))
        self.gridLayout_2.addWidget(self.spinBox_kernelIter, 3, 1, 1, 2)
        self.label_14 = QtGui.QLabel(self.groupBox_kinectFG)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_kinectFG, 3, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(17, 272, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 7, 0, 1, 1)
        self.groupBox_control = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_control.setObjectName(_fromUtf8("groupBox_control"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_control)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label = QtGui.QLabel(self.groupBox_control)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 2, 0, 1, 1)
        self.radioButton_joyAbs = QtGui.QRadioButton(self.groupBox_control)
        self.radioButton_joyAbs.setChecked(True)
        self.radioButton_joyAbs.setObjectName(_fromUtf8("radioButton_joyAbs"))
        self.gridLayout_3.addWidget(self.radioButton_joyAbs, 2, 2, 1, 1)
        self.radioButton_joyRel = QtGui.QRadioButton(self.groupBox_control)
        self.radioButton_joyRel.setObjectName(_fromUtf8("radioButton_joyRel"))
        self.gridLayout_3.addWidget(self.radioButton_joyRel, 2, 1, 1, 1)
        self.checkBox_autoCapture = QtGui.QCheckBox(self.groupBox_control)
        self.checkBox_autoCapture.setChecked(True)
        self.checkBox_autoCapture.setObjectName(_fromUtf8("checkBox_autoCapture"))
        self.gridLayout_3.addWidget(self.checkBox_autoCapture, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_control, 5, 0, 1, 2)
        ScrollAreaTracker.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(ScrollAreaTracker)
        self.comboBox_q1.setCurrentIndex(1)
        self.comboBox_kinMethod.setCurrentIndex(1)
        self.comboBox_prio.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ScrollAreaTracker)

    def retranslateUi(self, ScrollAreaTracker):
        ScrollAreaTracker.setWindowTitle(_translate("ScrollAreaTracker", "ScrollArea", None))
        self.groupBox_slam.setTitle(_translate("ScrollAreaTracker", "Mono Slam", None))
        self.groupBox_qualisys.setTitle(_translate("ScrollAreaTracker", "Qualisys Configuration", None))
        self.label_24.setText(_translate("ScrollAreaTracker", "Artificial Detection Delay", None))
        self.label_23.setText(_translate("ScrollAreaTracker", "Crazyflie Frame ID", None))
        self.comboBox_q1.setItemText(0, _translate("ScrollAreaTracker", "/Q0", None))
        self.comboBox_q1.setItemText(1, _translate("ScrollAreaTracker", "/Q1", None))
        self.comboBox_q1.setItemText(2, _translate("ScrollAreaTracker", "/Q2", None))
        self.label_22.setText(_translate("ScrollAreaTracker", "Wand Frame ID", None))
        self.comboBox_q0.setItemText(0, _translate("ScrollAreaTracker", "/Q0", None))
        self.comboBox_q0.setItemText(1, _translate("ScrollAreaTracker", "/Q1", None))
        self.comboBox_q0.setItemText(2, _translate("ScrollAreaTracker", "/Q2", None))
        self.doubleSpinBox_6.setSuffix(_translate("ScrollAreaTracker", " seconds", None))
        self.comboBox_tracker.setItemText(0, _translate("ScrollAreaTracker", "Qualisys Motion Tracker", None))
        self.comboBox_tracker.setItemText(1, _translate("ScrollAreaTracker", "Kinect", None))
        self.comboBox_tracker.setItemText(2, _translate("ScrollAreaTracker", "MonoSlam", None))
        self.pushButton_trackStart.setText(_translate("ScrollAreaTracker", "Enable Tracker", None))
        self.groupBox_kinectBG.setTitle(_translate("ScrollAreaTracker", "Background Detection", None))
        self.pushButton_reset.setText(_translate("ScrollAreaTracker", "Reset Background", None))
        self.comboBox_kinMethod.setItemText(0, _translate("ScrollAreaTracker", "Median", None))
        self.comboBox_kinMethod.setItemText(1, _translate("ScrollAreaTracker", "Minimum", None))
        self.label_17.setText(_translate("ScrollAreaTracker", "Method", None))
        self.label_11.setToolTip(_translate("ScrollAreaTracker", "Maximum distance in the scenem usually no need to change this", None))
        self.label_11.setText(_translate("ScrollAreaTracker", "Maximum Depth", None))
        self.doubleSpinBox_kinMaxDepth.setToolTip(_translate("ScrollAreaTracker", "Maximum distance in the scenem usually no need to change this", None))
        self.doubleSpinBox_kinMaxDepth.setSuffix(_translate("ScrollAreaTracker", " m", None))
        self.doubleSpinBox_kinObsTime.setSuffix(_translate("ScrollAreaTracker", " seconds", None))
        self.label_18.setText(_translate("ScrollAreaTracker", "Observation Time", None))
        self.label_2.setText(_translate("ScrollAreaTracker", "Foreground Distance", None))
        self.doubleSpinBox_kinFG.setSuffix(_translate("ScrollAreaTracker", " cm", None))
        self.groupBox_kinectFG.setTitle(_translate("ScrollAreaTracker", "Crazyflie Detection", None))
        self.spinBox_kernelSize.setSuffix(_translate("ScrollAreaTracker", " *2+1", None))
        self.label_21.setText(_translate("ScrollAreaTracker", "Depth Estimation", None))
        self.label_13.setToolTip(_translate("ScrollAreaTracker", "Maximum distance in the scenem usually no need to change this", None))
        self.label_13.setText(_translate("ScrollAreaTracker", "SizeTolerance", None))
        self.label_19.setText(_translate("ScrollAreaTracker", "Prioritise", None))
        self.label_12.setToolTip(_translate("ScrollAreaTracker", "How far away something has to be from the background to consider it foreground", None))
        self.label_12.setText(_translate("ScrollAreaTracker", "Detection Size", None))
        self.label_15.setToolTip(_translate("ScrollAreaTracker", "Maximum distance in the scenem usually no need to change this", None))
        self.label_15.setText(_translate("ScrollAreaTracker", "Opening Kernel Iterations", None))
        self.comboBox_kinDepth.setItemText(0, _translate("ScrollAreaTracker", "Center Pixel Depth", None))
        self.comboBox_kinDepth.setItemText(1, _translate("ScrollAreaTracker", "Median Depth", None))
        self.comboBox_kinDepth.setItemText(2, _translate("ScrollAreaTracker", "Closest", None))
        self.doubleSpinBox_tol.setToolTip(_translate("ScrollAreaTracker", "Maximum distance in the scenem usually no need to change this", None))
        self.doubleSpinBox_tol.setSuffix(_translate("ScrollAreaTracker", " cm", None))
        self.doubleSpinBox_kinDetSize.setSuffix(_translate("ScrollAreaTracker", " cm", None))
        self.comboBox_prio.setItemText(0, _translate("ScrollAreaTracker", "Distance from background", None))
        self.comboBox_prio.setItemText(1, _translate("ScrollAreaTracker", "Closest to Goal", None))
        self.comboBox_prio.setItemText(2, _translate("ScrollAreaTracker", "Closest to Camera", None))
        self.comboBox_prio.setItemText(3, _translate("ScrollAreaTracker", "Estimated Object Size", None))
        self.comboBox_prio.setItemText(4, _translate("ScrollAreaTracker", "Detection Size Pixels", None))
        self.label_14.setToolTip(_translate("ScrollAreaTracker", "Maximum distance in the scenem usually no need to change this", None))
        self.label_14.setText(_translate("ScrollAreaTracker", "Opening Kernel Size", None))
        self.groupBox_control.setTitle(_translate("ScrollAreaTracker", "Crazyflie Control", None))
        self.label.setText(_translate("ScrollAreaTracker", "Joy Control", None))
        self.radioButton_joyAbs.setToolTip(_translate("ScrollAreaTracker", "Move the flie relative to the optical axis of the kinect", None))
        self.radioButton_joyAbs.setText(_translate("ScrollAreaTracker", "Absolute", None))
        self.radioButton_joyRel.setToolTip(_translate("ScrollAreaTracker", "Move the flie relative to the flies orientation", None))
        self.radioButton_joyRel.setText(_translate("ScrollAreaTracker", "Relative", None))
        self.checkBox_autoCapture.setToolTip(_translate("ScrollAreaTracker", "Automatically Take over the flie control when trackable by kinect", None))
        self.checkBox_autoCapture.setText(_translate("ScrollAreaTracker", "Auto Capture", None))

